export const outputSchemaPrompt = [
  "Return only the structured fields requested by the schema.",
  "Required sections:",
  "A. Quick Verdict",
  "B. Scores with demo score, production score, and confidence level",
  "C. What The Code Does",
  "D. Bugs Found",
  "E. Type Safety Issues",
  "F. Security Review",
  "G. Performance Review",
  "H. Edge Cases Missing",
  "I. Code Quality & Maintainability",
  "J. Test Coverage Suggestions",
  "K. Refactored Code",
  "L. Final Recommendation",
  "Also include: Can this fail in production?, What would a senior engineer change?, What would break at scale?, Beginner explanation, and Before/After comparison.",
  "For bugsFound and typeSafetyIssues, include severity, issue, whyItHappens, location, and fix.",
  "For other findings, include severity, issue, evidence, and recommendation.",
  "Use empty arrays when no finding exists.",
  "For refactoredCode, set needed=false and leave language/code empty when a rewrite adds no real value.",
  "Use one decimal place for both scores.",
].join("\n");
